//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Public -WinUIVersion 3.0 -InputFile picture.json
//       
//       Input file:
//           picture.json (77514 bytes created 13:51+02:00 Feb 19 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    64 |
// |--------------------------+-------|
// | Expression animators     |     4 |
// | KeyFrame animators       |     6 |
// | Reference parameters     |     4 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     2 |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     1 |
// | CompositionSpriteShapes  |     4 |
// |--------------------------+-------|
// | Brushes                  |     4 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace AnimatedVisuals
{
    // Name:        Comp 1
    // Frame rate:  24 fps
    // Frame count: 28
    // Duration:    1166.7 mS
    // _____________________________________________________________________________________________
    // |           Marker           |           Constant           | Frame |   mS   |   Progress   |
    // |____________________________|______________________________|_______|________|______________|
    // | NormalToPressed_Start      | M_NormalToPressed_Start      |     0 |    0.0 | 0F           |
    // | NormalToPressed_End        | M_NormalToPressed_End        |     9 |  375.0 | 0.323214293F |
    // | PointerOverToPressed_Start | M_PointerOverToPressed_Start |     9 |  375.0 | 0.323214293F |
    // | PointerOverToPressed_End   | M_PointerOverToPressed_End   |    19 |  791.7 | 0.680357158F |
    // | PressedToNormal_Start      | M_PressedToNormal_Start      |    20 |  833.3 | 0.716071427F |
    // | PressedToNormal_End        | M_PressedToNormal_End        |    28 | 1166.7 | 1F           |
    // | PressedToPointerOver_Start | M_PressedToPointerOver_Start |    28 | 1166.7 | 1F           |
    // | PressedToPointerOver_End   | M_PressedToPointerOver_End   |    28 | 1166.7 | 1F           |
    // ---------------------------------------------------------------------------------------------
    sealed partial class Picture
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 1.167 seconds.
        internal const long c_durationTicks = 11666666;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.323214293F;

        // Marker: PointerOverToPressed_Start.
        internal const float M_PointerOverToPressed_Start = 0.323214293F;

        // Marker: PointerOverToPressed_End.
        internal const float M_PointerOverToPressed_End = 0.680357158F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.716071427F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 1F;

        // Marker: PressedToPointerOver_Start.
        internal const float M_PressedToPointerOver_Start = 1F;

        // Marker: PressedToPointerOver_End.
        internal const float M_PressedToPointerOver_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new Picture_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 28d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 24d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(11666666);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 28d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPressed_Start", 0d },
                { "NormalToPressed_End", 0.323214285714286 },
                { "PointerOverToPressed_Start", 0.323214285714286 },
                { "PointerOverToPressed_End", 0.680357142857143 },
                { "PressedToNormal_Start", 0.716071428571429 },
                { "PressedToNormal_End", 1d },
                { "PressedToPointerOver_Start", 1d },
                { "PressedToPointerOver_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class Picture_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 11666666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionContainerShape _containerShape;
            CompositionPath _path_0;
            CompositionPath _path_1;
            CompositionPath _path_2;
            CompositionPath _path_3;
            CompositionPathGeometry _pathGeometry_2;
            CompositionPathGeometry _pathGeometry_3;
            CompositionSpriteShape _spriteShape_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - - Layer aggregator
            // - - ShapeGroup: Group 1
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(16F, 17F));
                    builder.AddLine(new Vector2(-16F, 17F));
                    builder.AddCubicBezier(new Vector2(-18.2000008F, 17F), new Vector2(-20F, 15.1999998F), new Vector2(-20F, 13F));
                    builder.AddLine(new Vector2(-20F, -13F));
                    builder.AddCubicBezier(new Vector2(-20F, -15.1999998F), new Vector2(-18.2000008F, -17F), new Vector2(-16F, -17F));
                    builder.AddLine(new Vector2(16F, -17F));
                    builder.AddCubicBezier(new Vector2(18.2000008F, -17F), new Vector2(20F, -15.1999998F), new Vector2(20F, -13F));
                    builder.AddLine(new Vector2(20F, 13F));
                    builder.AddCubicBezier(new Vector2(20F, 15.1999998F), new Vector2(18.2000008F, 17F), new Vector2(16F, 17F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: sun
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, -3F));
                    builder.AddCubicBezier(new Vector2(-1.65699995F, -3F), new Vector2(-3F, -1.65699995F), new Vector2(-3F, 0F));
                    builder.AddCubicBezier(new Vector2(-3F, 1.65699995F), new Vector2(-1.65699995F, 3F), new Vector2(0F, 3F));
                    builder.AddCubicBezier(new Vector2(1.65699995F, 3F), new Vector2(3F, 1.65699995F), new Vector2(3F, 0F));
                    builder.AddCubicBezier(new Vector2(3F, -1.65699995F), new Vector2(1.65699995F, -3F), new Vector2(0F, -3F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, -8F));
                    builder.AddCubicBezier(new Vector2(0F, -8F), new Vector2(-11F, 8F), new Vector2(-11F, 8F));
                    builder.AddCubicBezier(new Vector2(-11F, 8F), new Vector2(11F, 8F), new Vector2(11F, 8F));
                    builder.AddCubicBezier(new Vector2(11F, 8F), new Vector2(0F, -8F), new Vector2(0F, -8F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: mountains Offset:<-24, -24>
            // - Path
            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-4.96899986F, -0.773000002F));
                    builder.AddCubicBezier(new Vector2(-4.96899986F, -0.773000002F), new Vector2(-11F, 8F), new Vector2(-11F, 8F));
                    builder.AddCubicBezier(new Vector2(-11F, 8F), new Vector2(1.06299996F, 8F), new Vector2(1.06299996F, 8F));
                    builder.AddCubicBezier(new Vector2(1.06299996F, 8F), new Vector2(-4.96899986F, -0.773000002F), new Vector2(-4.96899986F, -0.773000002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-4.03900003F, -2.125F));
                    builder.AddCubicBezier(new Vector2(-4.03900003F, -2.125F), new Vector2(-11F, 8F), new Vector2(-11F, 8F));
                    builder.AddCubicBezier(new Vector2(-11F, 8F), new Vector2(2.92199993F, 8F), new Vector2(2.92199993F, 8F));
                    builder.AddCubicBezier(new Vector2(2.92199993F, 8F), new Vector2(-4.03900003F, -2.125F), new Vector2(-4.03900003F, -2.125F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: mountains Offset:<-24, -24>
            // - Path
            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0.787F, -9.14500046F));
                    builder.AddCubicBezier(new Vector2(0.787F, -9.14500046F), new Vector2(-11F, 8F), new Vector2(-11F, 8F));
                    builder.AddCubicBezier(new Vector2(-11F, 8F), new Vector2(12.5740004F, 8F), new Vector2(12.5740004F, 8F));
                    builder.AddCubicBezier(new Vector2(12.5740004F, 8F), new Vector2(0.787F, -9.14500046F), new Vector2(0.787F, -9.14500046F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_6()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, -5F));
                    builder.AddCubicBezier(new Vector2(0F, -5F), new Vector2(-8F, 5F), new Vector2(-8F, 5F));
                    builder.AddCubicBezier(new Vector2(-8F, 5F), new Vector2(8F, 5F), new Vector2(8F, 5F));
                    builder.AddCubicBezier(new Vector2(8F, 5F), new Vector2(0F, -5F), new Vector2(0F, -5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: mountains Offset:<-24, -24>
            // - Path
            CanvasGeometry Geometry_7()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-5.875F, -12.3439999F));
                    builder.AddCubicBezier(new Vector2(-5.875F, -12.3439999F), new Vector2(-19.75F, 5F), new Vector2(-19.75F, 5F));
                    builder.AddCubicBezier(new Vector2(-19.75F, 5F), new Vector2(8F, 5F), new Vector2(8F, 5F));
                    builder.AddCubicBezier(new Vector2(8F, 5F), new Vector2(-5.875F, -12.3439999F), new Vector2(-5.875F, -12.3439999F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_8()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-4.80000019F, -11F));
                    builder.AddCubicBezier(new Vector2(-4.80000019F, -11F), new Vector2(-17.6000004F, 5F), new Vector2(-17.6000004F, 5F));
                    builder.AddCubicBezier(new Vector2(-17.6000004F, 5F), new Vector2(8F, 5F), new Vector2(8F, 5F));
                    builder.AddCubicBezier(new Vector2(8F, 5F), new Vector2(-4.80000019F, -11F), new Vector2(-4.80000019F, -11F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: mountains Offset:<-24, -24>
            // - Path
            CanvasGeometry Geometry_9()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(1.03400004F, -3.70799994F));
                    builder.AddCubicBezier(new Vector2(1.03400004F, -3.70799994F), new Vector2(-5.93200016F, 5F), new Vector2(-5.93200016F, 5F));
                    builder.AddCubicBezier(new Vector2(-5.93200016F, 5F), new Vector2(8F, 5F), new Vector2(8F, 5F));
                    builder.AddCubicBezier(new Vector2(8F, 5F), new Vector2(1.03400004F, -3.70799994F), new Vector2(1.03400004F, -3.70799994F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 1
            CompositionColorBrush ColorBrush_AlmostDarkOrange_FFF57C00()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF5, 0x7C, 0x00));
            }

            // - - Layer aggregator
            // Transforms: mountains Offset:<-24, -24>
            CompositionColorBrush ColorBrush_AlmostFirebrick_FFBF360C()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xBF, 0x36, 0x0C));
            }

            // - - Layer aggregator
            // Transforms: sun
            CompositionColorBrush ColorBrush_AlmostLemonChiffon_FFFFF9C4()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xF9, 0xC4));
            }

            // - - Layer aggregator
            // Transforms: mountains Offset:<-24, -24>
            CompositionColorBrush ColorBrush_AlmostSaddleBrown_FF942A09()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x94, 0x2A, 0x09));
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape()
            {
                if (_containerShape != null) { return _containerShape; }
                var result = _containerShape = _c.CreateContainerShape();
                result.Offset = new Vector2(24F, 24F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_0());
                // Transforms: sun
                shapes.Add(SpriteShape_1());
                // Transforms: mountains Offset:<-24, -24>
                shapes.Add(SpriteShape_2());
                // Transforms: mountains Offset:<-24, -24>
                shapes.Add(SpriteShape_3());
                return result;
            }

            CompositionPath Path_0()
            {
                if (_path_0 != null) { return _path_0; }
                var result = _path_0 = new CompositionPath(Geometry_2());
                return result;
            }

            CompositionPath Path_1()
            {
                if (_path_1 != null) { return _path_1; }
                var result = _path_1 = new CompositionPath(Geometry_4());
                return result;
            }

            CompositionPath Path_2()
            {
                if (_path_2 != null) { return _path_2; }
                var result = _path_2 = new CompositionPath(Geometry_6());
                return result;
            }

            CompositionPath Path_3()
            {
                if (_path_3 != null) { return _path_3; }
                var result = _path_3 = new CompositionPath(Geometry_8());
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 1
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
            }

            // - - Layer aggregator
            // Transforms: sun
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
            }

            // - - Layer aggregator
            // Transforms: mountains Offset:<-24, -24>
            CompositionPathGeometry PathGeometry_2()
            {
                if (_pathGeometry_2 != null) { return _pathGeometry_2; }
                var result = _pathGeometry_2 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // Transforms: mountains Offset:<-24, -24>
            CompositionPathGeometry PathGeometry_3()
            {
                if (_pathGeometry_3 != null) { return _pathGeometry_3; }
                var result = _pathGeometry_3 = _c.CreatePathGeometry();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                var result = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ColorBrush_AlmostDarkOrange_FFF57C00();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(PathGeometry_1());
                result.FillBrush = ColorBrush_AlmostLemonChiffon_FFFFF9C4();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<-4, 0>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, -4F, 0F), ColorBrush_AlmostSaddleBrown_FF942A09());;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<7, 3>
                var geometry = PathGeometry_3();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 7F, 3F), ColorBrush_AlmostFirebrick_FFBF360C());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                propertySet.InsertScalar("t0", 0F);
                propertySet.InsertScalar("t1", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_1;
            }

            // - - - Layer aggregator
            // - Transforms: mountains Offset:<-24, -24>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_0(), StepThenHoldEasingFunction());
                // Frame 1.
                result.InsertKeyFrame(0.0357142873F, Path_0(), HoldThenStepEasingFunction());
                // Frame 8.
                result.InsertKeyFrame(0.285714298F, new CompositionPath(Geometry_3()), CubicBezierEasingFunction_0());
                // Frame 10.
                result.InsertKeyFrame(0.357142866F, Path_1(), CubicBezierEasingFunction_0());
                // Frame 18.
                result.InsertKeyFrame(0.642857134F, Path_1(), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, new CompositionPath(Geometry_5()), CubicBezierEasingFunction_0());
                // Frame 27.
                result.InsertKeyFrame(0.964285731F, Path_0(), CubicBezierEasingFunction_1());
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: mountains Offset:<-24, -24>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_1()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_2(), StepThenHoldEasingFunction());
                // Frame 1.
                result.InsertKeyFrame(0.0357142873F, Path_2(), HoldThenStepEasingFunction());
                // Frame 8.
                result.InsertKeyFrame(0.285714298F, new CompositionPath(Geometry_7()), CubicBezierEasingFunction_0());
                // Frame 10.
                result.InsertKeyFrame(0.357142866F, Path_3(), CubicBezierEasingFunction_0());
                // Frame 18.
                result.InsertKeyFrame(0.642857134F, Path_3(), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, new CompositionPath(Geometry_9()), CubicBezierEasingFunction_0());
                // Frame 27.
                result.InsertKeyFrame(0.964285731F, Path_2(), CubicBezierEasingFunction_1());
                return result;
            }

            ScalarKeyFrameAnimation t0ScalarAnimation_0_to_1()
            {
                // Frame 2.
                var result = CreateScalarKeyFrameAnimation(0.0714285821F, 0F, StepThenHoldEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 9.
                result.InsertKeyFrame(0.321428537F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.833000004F, 0.861000001F)));
                // Frame 11.
                result.InsertKeyFrame(0.392857164F, 0F, StepThenHoldEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.607142806F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.023F, 1F), new Vector2(0.998000026F, 0F)));
                return result;
            }

            ScalarKeyFrameAnimation t1ScalarAnimation_0_to_1()
            {
                // Frame 17.
                var result = CreateScalarKeyFrameAnimation(0.607142866F, 0F, StepThenHoldEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 23.
                result.InsertKeyFrame(0.821428537F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.0829999968F), new Vector2(0.833000004F, 0.86500001F)));
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(48F, 48F);
                result.Shapes.Add(ContainerShape());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Layer aggregator
            // Transforms: sun
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(11F, -8F), StepThenHoldEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 2.
                result.InsertKeyFrame(0.0714285746F, new Vector2(11F, -8F), HoldThenStepEasingFunction());
                // Frame 9.
                result.InsertExpressionKeyFrame(0.321428537F, "Pow(1-_.t0,3)*Vector2(11,-8)+(3*Square(1-_.t0)*_.t0*Vector2(-0.25,-15.688))+(3*(1-_.t0)*Square(_.t0)*Vector2(-12.572,-7.115))+(Pow(_.t0,3)*Vector2(-12.572,-7.115))", StepThenHoldEasingFunction());
                // Frame 9.
                result.InsertKeyFrame(0.321428567F, new Vector2(-12.5719995F, -7.11499977F), StepThenHoldEasingFunction());
                // Frame 11.
                result.InsertKeyFrame(0.392857134F, new Vector2(-11.125F, -8.06599998F), _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.572000027F), new Vector2(0.833000004F, 0.958000004F)));
                // Frame 17.
                result.InsertExpressionKeyFrame(0.607142806F, "Pow(1-_.t0,3)*Vector2(-11.125,-8.066)+(3*Square(1-_.t0)*_.t0*Vector2(-11.125,-8.066))+(3*(1-_.t0)*Square(_.t0)*Vector2(-11.143,-8.035))+(Pow(_.t0,3)*Vector2(-11.125,-8.051))", StepThenHoldEasingFunction());
                // Frame 23.
                result.InsertExpressionKeyFrame(0.821428537F, "Pow(1-_.t1,3)*Vector2(-11.125,-8.051)+(3*Square(1-_.t1)*_.t1*Vector2(-3.132,-12.277))+(3*(1-_.t1)*Square(_.t1)*Vector2(5.847,-12.776))+(Pow(_.t1,3)*Vector2(12.618,-6.738))", StepThenHoldEasingFunction());
                // Frame 23.
                result.InsertKeyFrame(0.821428597F, new Vector2(12.618F, -6.73799992F), StepThenHoldEasingFunction());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, new Vector2(11F, -8F), _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.558000028F), new Vector2(0.666999996F, 1F)));
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), StepThenHoldEasingFunction());
                // Frame 2.
                result.InsertKeyFrame(0.0714285746F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 6.
                result.InsertKeyFrame(0.214285716F, new Vector2(0.970000029F, 1.02999997F), CubicBezierEasingFunction_0());
                // Frame 10.
                result.InsertKeyFrame(0.357142866F, new Vector2(1.02999997F, 0.970000029F), CubicBezierEasingFunction_0());
                // Frame 12.
                result.InsertKeyFrame(0.428571433F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                // Frame 16.
                result.InsertKeyFrame(0.571428597F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                // Frame 18.
                result.InsertKeyFrame(0.642857134F, new Vector2(1.02999997F, 0.970000029F), CubicBezierEasingFunction_0());
                // Frame 22.
                result.InsertKeyFrame(0.785714269F, new Vector2(0.970000029F, 1.02999997F), CubicBezierEasingFunction_0());
                // Frame 26.
                result.InsertKeyFrame(0.928571403F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                return result;
            }

            internal Picture_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(48F, 48F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape.StartAnimation("Scale", ScaleVector2Animation(), AnimationController_0());
                _pathGeometry_2.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
                _pathGeometry_3.StartAnimation("Path", PathKeyFrameAnimation_1(), AnimationController_0());
                _spriteShape_1.StartAnimation("Offset", OffsetVector2Animation(), AnimationController_0());
                _root.Properties.StartAnimation("t0", t0ScalarAnimation_0_to_1(), AnimationController_0());
                _root.Properties.StartAnimation("t1", t1ScalarAnimation_0_to_1(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape.StopAnimation("Scale");
                _pathGeometry_2.StopAnimation("Path");
                _pathGeometry_3.StopAnimation("Path");
                _spriteShape_1.StopAnimation("Offset");
                _root.Properties.StopAnimation("t0");
                _root.Properties.StopAnimation("t1");
            }

        }
    }
}
