[build]
target-dir = "target"

[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "target-cpu=x86-64-v2",
  "-C", "target-feature=+crt-static"
]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[alias]
build_x64 = "build --target x86_64-pc-windows-msvc --bin MSDefenderWMIRetriever-X64 --verbose --release"
build_arm64 = "build --target aarch64-pc-windows-msvc --bin MSDefenderWMIRetriever-ARM64 --verbose --release"
