name: Bug Report 🐛
description: File a bug report
# title: "[Bug]: "
labels: ["Needs Triage 🤔"]
assignees:
  - HotCakeX
body:
  - type: markdown
    attributes:
      value: |
        *Thanks for taking the time to fill out this bug report!*
  - type: dropdown
    id: version
    attributes:
      label: Product
      description: Which Product Does This Bug Belong To?
      options:
        - Harden System Security App
        - AppControl Manager
    validations:
      required: true
  - type: checkboxes
    id: Genuine-Windows
    attributes:
      label: Is your Windows Installation Genuine?
      options:
        - label: Yes, I acknowledge that the installation media (such as ISO file) of the Windows OS I'm using was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯
          required: true
  - type: checkboxes
    id: No-3rd-Party-Tool
    attributes:
      label: Have you used any other 3rd party tools to modify your Windows installation?
      options:
        - label: If you used any other 3rd party tools to modify your Windows installation, they can be causing the problem you're experiencing.
          required: false
  - type: checkboxes
    id: Read-FAQ
    attributes:
      label: Did You Read The Frequently Asked Questions?
      options:
        - label: Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.
          required: true
  - type: textarea
    id: Explanation
    attributes:
      label: Please Explain The Bug
      description: Please explain the bug and be as detailed as possible. Screenshots will help too.
      placeholder: "There is a problem with..."
    validations:
      required: true
  - type: textarea
    id: Error-Details
    attributes:
      label: Error Details
      description: Any error messages you received or app logs you have can be pasted here.
    validations:
      required: false
  - type: upload
    id: Error-Details-File-Upload
    attributes:
      label: Upload any files you'd like to share as ZIP files.
      description: If you'd like to upload file(s) that are related to the issue or can help reproduce the problem you're reporting, please zip them first and then upload them here.
    validations:
      required: false
  - type: input
    attributes:
      label: Windows Version
      description: The version or build number of the Windows you're using. You can view it in the Windows Settings -> System -> About. You can also access that area by pressing `Win + R` keys simultaneously, typing `ms-settings:about` and pressing enter.
      placeholder: E.g., 25H2 - 26200.8117
    validations:
      required: true
  - type: input
    attributes:
      label: App Version
      description: The version of the app you are using. You can view it in the app's Settings page -> About. You can also view app versions in the Windows Settings -> Installed Apps -> Select an app and choose "Advanced options".
      placeholder: E.g., 2.0.56.0
    validations:
      required: true
