name: Bug Report 🐛
description: File a bug report
# title: "[Bug]: "
labels: ["Needs Triage 🤔"]
assignees:
  - HotCakeX
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
      label: Product
      description: Which Product Does This Bug Belong To?
      options:
        - Harden System Security App
        - AppControl Manager
    validations:
      required: true
  - type: checkboxes
    id: Requirements
    attributes:
      label: Does Your System Meet The Requirements?
      description: Depending on which product your bug belongs to, please make sure you have read their requirements and meet them [Harden System Security Requirements](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Harden-System-Security#supported-operation-systems), [AppControl Manager](https://github.com/HotCakeX/Harden-Windows-Security/wiki/AppControl-Manager#supported-operation-systems)
      options:
        - label: Yes, I acknowledge that I've read the requirements and my system meets them. 👍
          required: true
  - type: checkboxes
    id: Genuine-Windows
    attributes:
      label: Is your Windows Installation Genuine?
      options:
        - label: Yes, I acknowledge that the installation media (such as ISO file) of the Windows OS I used was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯
          required: true
  - type: checkboxes
    id: No-3rd-Party-Tool
    attributes:
      label: Have you used any other 3rd party tools to modify your Windows installation?
      options:
        - label: If you used any other 3rd party tools to modify your Windows installation, they can be causing the problem you're experiencing.
          required: false
  - type: checkboxes
    id: Read-FAQ
    attributes:
      label: Did You Read The Frequently Asked Questions?
      options:
        - label: Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.
          required: true
  - type: textarea
    id: Explanation
    attributes:
      label: Please Explain The Bug
      description: Please explain the bug and be as detailed as possible. Screenshots will help too.
      placeholder: "There is a problem with..."
    validations:
      required: true
  - type: textarea
    id: Error-Details
    attributes:
      label: Error Details
      description: Any error messages or codes you received.
    validations:
      required: false
