//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.1.240821.1+077322fa26
//       
//       Command:
//           LottieGen -Language CSharp -Public -WinUIVersion 3.0 -InputFile StarYellow.json
//       
//       Input file:
//           StarYellow.json (163661 bytes created 15:19+02:00 Nov 17 2024)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    94 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |    12 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |    10 |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     1 |
// | CompositionSpriteShapes  |    12 |
// |--------------------------+-------|
// | Brushes                  |     3 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace AnimatedVisuals
{
    // Name:        star-2
    // Frame rate:  24 fps
    // Frame count: 28
    // Duration:    1166.7 mS
    // _____________________________________________________________________________________________
    // |           Marker           |           Constant           | Frame |   mS   |   Progress   |
    // |____________________________|______________________________|_______|________|______________|
    // | NormalToPressed_Start      | M_NormalToPressed_Start      |     0 |    0.0 | 0F           |
    // | NormalToPressed_End        | M_NormalToPressed_End        |     9 |  375.0 | 0.323214293F |
    // | PointerOverToPressed_Start | M_PointerOverToPressed_Start |     9 |  375.0 | 0.323214293F |
    // | PointerOverToPressed_End   | M_PointerOverToPressed_End   |    19 |  791.7 | 0.680357158F |
    // | PressedToNormal_Start      | M_PressedToNormal_Start      |    20 |  833.3 | 0.716071427F |
    // | PressedToNormal_End        | M_PressedToNormal_End        |    28 | 1166.7 | 1F           |
    // | PressedToPointerOver_Start | M_PressedToPointerOver_Start |    28 | 1166.7 | 1F           |
    // | PressedToPointerOver_End   | M_PressedToPointerOver_End   |    28 | 1166.7 | 1F           |
    // ---------------------------------------------------------------------------------------------
    sealed partial class StarYellow
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 1.167 seconds.
        internal const long c_durationTicks = 11666666;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.323214293F;

        // Marker: PointerOverToPressed_Start.
        internal const float M_PointerOverToPressed_Start = 0.323214293F;

        // Marker: PointerOverToPressed_End.
        internal const float M_PointerOverToPressed_End = 0.680357158F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.716071427F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 1F;

        // Marker: PressedToPointerOver_Start.
        internal const float M_PressedToPointerOver_Start = 1F;

        // Marker: PressedToPointerOver_End.
        internal const float M_PressedToPointerOver_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res =
                new StarYellow_AnimatedVisual(
                    compositor
                    );
            res.CreateAnimations();
            return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 28d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 24d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(11666666);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 28d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPressed_Start", 0d },
                { "NormalToPressed_End", 0.323214285714286 },
                { "PointerOverToPressed_Start", 0.323214285714286 },
                { "PointerOverToPressed_End", 0.680357142857143 },
                { "PressedToNormal_Start", 0.716071428571429 },
                { "PressedToNormal_End", 1d },
                { "PressedToPointerOver_Start", 1d },
                { "PressedToPointerOver_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class StarYellow_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 11666666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostDarkOrange_FFEB7900;
            CompositionColorBrush _colorBrush_AlmostGold_FFFADB00;
            CompositionColorBrush _colorBrush_AlmostOrange_FFF5BC00;
            CompositionContainerShape _containerShape;
            CompositionPath _path_0;
            CompositionPath _path_1;
            CompositionPath _path_2;
            CompositionPath _path_3;
            CompositionPath _path_4;
            CompositionPath _path_5;
            CompositionPath _path_6;
            CompositionPath _path_7;
            CompositionPath _path_8;
            CompositionPath _path_9;
            CompositionPathGeometry _pathGeometry_00;
            CompositionPathGeometry _pathGeometry_01;
            CompositionPathGeometry _pathGeometry_02;
            CompositionPathGeometry _pathGeometry_03;
            CompositionPathGeometry _pathGeometry_04;
            CompositionPathGeometry _pathGeometry_06;
            CompositionPathGeometry _pathGeometry_07;
            CompositionPathGeometry _pathGeometry_08;
            CompositionPathGeometry _pathGeometry_09;
            CompositionPathGeometry _pathGeometry_10;
            CompositionSpriteShape _spriteShape_11;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            CanvasGeometry Geometry_00()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.55000019F, -7F));
                    builder.AddCubicBezier(new Vector2(5.55000019F, -7F), new Vector2(0F, -22.9559994F), new Vector2(0F, -22.9559994F));
                    builder.AddCubicBezier(new Vector2(0F, -22.9559994F), new Vector2(-5.55000019F, -7F), new Vector2(-5.55000019F, -7F));
                    builder.AddCubicBezier(new Vector2(-5.55000019F, -7F), new Vector2(5.55000019F, -7F), new Vector2(5.55000019F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - ShapeGroup: Group 6
            // - Path
            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.55000019F, -7F));
                    builder.AddCubicBezier(new Vector2(5.55000019F, -7F), new Vector2(0F, -6.98099995F), new Vector2(0F, -6.98099995F));
                    builder.AddCubicBezier(new Vector2(0F, -6.98099995F), new Vector2(-5.55000019F, -7F), new Vector2(-5.55000019F, -7F));
                    builder.AddCubicBezier(new Vector2(-5.55000019F, -7F), new Vector2(5.55000019F, -7F), new Vector2(5.55000019F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-15.2729998F, 20.9559994F));
                    builder.AddCubicBezier(new Vector2(-15.2729998F, 20.9559994F), new Vector2(0F, 11.5860004F), new Vector2(0F, 11.5860004F));
                    builder.AddCubicBezier(new Vector2(0F, 11.5860004F), new Vector2(-9.46500015F, 4.25600004F), new Vector2(-9.46500015F, 4.25600004F));
                    builder.AddCubicBezier(new Vector2(-9.46500015F, 4.25600004F), new Vector2(-15.2729998F, 20.9559994F), new Vector2(-15.2729998F, 20.9559994F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - ShapeGroup: Group 6
            // - Path
            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-4.74800014F, 7.90600014F));
                    builder.AddCubicBezier(new Vector2(-4.74800014F, 7.90600014F), new Vector2(0F, 11.5860004F), new Vector2(0F, 11.5860004F));
                    builder.AddCubicBezier(new Vector2(0F, 11.5860004F), new Vector2(-9.46500015F, 4.25600004F), new Vector2(-9.46500015F, 4.25600004F));
                    builder.AddCubicBezier(new Vector2(-9.46500015F, 4.25600004F), new Vector2(-4.74800014F, 7.90600014F), new Vector2(-4.74800014F, 7.90600014F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(9.46500015F, 4.25600004F));
                    builder.AddCubicBezier(new Vector2(9.46500015F, 4.25600004F), new Vector2(0F, 11.5860004F), new Vector2(0F, 11.5860004F));
                    builder.AddCubicBezier(new Vector2(0F, 11.5860004F), new Vector2(15.2729998F, 20.9559994F), new Vector2(15.2729998F, 20.9559994F));
                    builder.AddCubicBezier(new Vector2(15.2729998F, 20.9559994F), new Vector2(9.46500015F, 4.25600004F), new Vector2(9.46500015F, 4.25600004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - ShapeGroup: Group 6
            // - Path
            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(9.46500015F, 4.25600004F));
                    builder.AddCubicBezier(new Vector2(9.46500015F, 4.25600004F), new Vector2(0F, 11.5860004F), new Vector2(0F, 11.5860004F));
                    builder.AddCubicBezier(new Vector2(0F, 11.5860004F), new Vector2(4.69799995F, 7.90600014F), new Vector2(4.69799995F, 7.90600014F));
                    builder.AddCubicBezier(new Vector2(4.69799995F, 7.90600014F), new Vector2(9.46500015F, 4.25600004F), new Vector2(9.46500015F, 4.25600004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-5.54899979F, -7F));
                    builder.AddCubicBezier(new Vector2(-5.54899979F, -7F), new Vector2(-24F, -7F), new Vector2(-24F, -7F));
                    builder.AddCubicBezier(new Vector2(-24F, -7F), new Vector2(-9.46899986F, 4.24900007F), new Vector2(-9.46899986F, 4.24900007F));
                    builder.AddCubicBezier(new Vector2(-9.46899986F, 4.24900007F), new Vector2(-5.54899979F, -7F), new Vector2(-5.54899979F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - ShapeGroup: Group 6
            // - Path
            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-5.54899979F, -7F));
                    builder.AddCubicBezier(new Vector2(-5.54899979F, -7F), new Vector2(-7.52699995F, -1.29999995F), new Vector2(-7.52699995F, -1.29999995F));
                    builder.AddCubicBezier(new Vector2(-7.52699995F, -1.29999995F), new Vector2(-9.46899986F, 4.24900007F), new Vector2(-9.46899986F, 4.24900007F));
                    builder.AddCubicBezier(new Vector2(-9.46899986F, 4.24900007F), new Vector2(-5.54899979F, -7F), new Vector2(-5.54899979F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(24F, -7F));
                    builder.AddCubicBezier(new Vector2(24F, -7F), new Vector2(5.54899979F, -7F), new Vector2(5.54899979F, -7F));
                    builder.AddCubicBezier(new Vector2(5.54899979F, -7F), new Vector2(9.45899963F, 4.24900007F), new Vector2(9.45899963F, 4.24900007F));
                    builder.AddCubicBezier(new Vector2(9.45899963F, 4.24900007F), new Vector2(24F, -7F), new Vector2(24F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - ShapeGroup: Group 6
            // - Path
            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(7.52699995F, -1.29999995F));
                    builder.AddCubicBezier(new Vector2(7.52699995F, -1.29999995F), new Vector2(5.54899979F, -7F), new Vector2(5.54899979F, -7F));
                    builder.AddCubicBezier(new Vector2(5.54899979F, -7F), new Vector2(9.45899963F, 4.24900007F), new Vector2(9.45899963F, 4.24900007F));
                    builder.AddCubicBezier(new Vector2(9.45899963F, 4.24900007F), new Vector2(7.52699995F, -1.29999995F), new Vector2(7.52699995F, -1.29999995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - ShapeGroup: Group 6
            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-9.46899986F, 4.24900007F));
                    builder.AddLine(new Vector2(0F, 11.5860004F));
                    builder.AddLine(new Vector2(9.47299957F, 4.26300001F));
                    builder.AddLine(new Vector2(5.54899979F, -7F));
                    builder.AddLine(new Vector2(-5.54899979F, -7F));
                    builder.AddLine(new Vector2(-9.46899986F, 4.24900007F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.55000019F, -7F));
                    builder.AddCubicBezier(new Vector2(5.55000019F, -7F), new Vector2(0F, -7.00600004F), new Vector2(0F, -7.00600004F));
                    builder.AddCubicBezier(new Vector2(0F, -7.00600004F), new Vector2(-5.55000019F, -7F), new Vector2(-5.55000019F, -7F));
                    builder.AddCubicBezier(new Vector2(-5.55000019F, -7F), new Vector2(0.0120000001F, -5.75F), new Vector2(0.0120000001F, -5.75F));
                    builder.AddCubicBezier(new Vector2(0.0120000001F, -5.75F), new Vector2(5.55000019F, -7F), new Vector2(5.55000019F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: star 2
            // - Path
            CanvasGeometry Geometry_12()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.55000019F, -7F));
                    builder.AddCubicBezier(new Vector2(5.55000019F, -7F), new Vector2(0F, -22.9559994F), new Vector2(0F, -22.9559994F));
                    builder.AddCubicBezier(new Vector2(0F, -22.9559994F), new Vector2(-5.55000019F, -7F), new Vector2(-5.55000019F, -7F));
                    builder.AddCubicBezier(new Vector2(-5.55000019F, -7F), new Vector2(0F, -5.55000019F), new Vector2(0F, -5.55000019F));
                    builder.AddCubicBezier(new Vector2(0F, -5.55000019F), new Vector2(5.55000019F, -7F), new Vector2(5.55000019F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_13()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-4.77299976F, 7.85599995F));
                    builder.AddCubicBezier(new Vector2(-4.77299976F, 7.85599995F), new Vector2(0F, 11.5860004F), new Vector2(0F, 11.5860004F));
                    builder.AddCubicBezier(new Vector2(0F, 11.5860004F), new Vector2(-3.74300003F, 6.28900003F), new Vector2(-3.74300003F, 6.28900003F));
                    builder.AddCubicBezier(new Vector2(-3.74300003F, 6.28900003F), new Vector2(-9.46500015F, 4.25600004F), new Vector2(-9.46500015F, 4.25600004F));
                    builder.AddCubicBezier(new Vector2(-9.46500015F, 4.25600004F), new Vector2(-4.77299976F, 7.85599995F), new Vector2(-4.77299976F, 7.85599995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: star 2
            // - Path
            CanvasGeometry Geometry_14()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-15.2729998F, 20.9559994F));
                    builder.AddCubicBezier(new Vector2(-15.2729998F, 20.9559994F), new Vector2(0F, 11.5860004F), new Vector2(0F, 11.5860004F));
                    builder.AddCubicBezier(new Vector2(0F, 11.5860004F), new Vector2(-4.08099985F, 6.90799999F), new Vector2(-4.08099985F, 6.90799999F));
                    builder.AddCubicBezier(new Vector2(-4.08099985F, 6.90799999F), new Vector2(-9.46500015F, 4.25600004F), new Vector2(-9.46500015F, 4.25600004F));
                    builder.AddCubicBezier(new Vector2(-9.46500015F, 4.25600004F), new Vector2(-15.2729998F, 20.9559994F), new Vector2(-15.2729998F, 20.9559994F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_15()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(9.46500015F, 4.25600004F));
                    builder.AddCubicBezier(new Vector2(9.46500015F, 4.25600004F), new Vector2(3.42400002F, 5.90999985F), new Vector2(3.42400002F, 5.90999985F));
                    builder.AddCubicBezier(new Vector2(3.42400002F, 5.90999985F), new Vector2(0F, 11.5860004F), new Vector2(0F, 11.5860004F));
                    builder.AddCubicBezier(new Vector2(0F, 11.5860004F), new Vector2(4.82800007F, 7.85599995F), new Vector2(4.82800007F, 7.85599995F));
                    builder.AddCubicBezier(new Vector2(4.82800007F, 7.85599995F), new Vector2(9.46500015F, 4.25600004F), new Vector2(9.46500015F, 4.25600004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: star 2
            // - Path
            CanvasGeometry Geometry_16()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(9.46500015F, 4.25600004F));
                    builder.AddCubicBezier(new Vector2(9.46500015F, 4.25600004F), new Vector2(3.68499994F, 7.00600004F), new Vector2(3.68499994F, 7.00600004F));
                    builder.AddCubicBezier(new Vector2(3.68499994F, 7.00600004F), new Vector2(0F, 11.5860004F), new Vector2(0F, 11.5860004F));
                    builder.AddCubicBezier(new Vector2(0F, 11.5860004F), new Vector2(15.1780005F, 20.9559994F), new Vector2(15.1780005F, 20.9559994F));
                    builder.AddCubicBezier(new Vector2(15.1780005F, 20.9559994F), new Vector2(9.46500015F, 4.25600004F), new Vector2(9.46500015F, 4.25600004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_17()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-5.55200005F, -7F));
                    builder.AddCubicBezier(new Vector2(-5.55200005F, -7F), new Vector2(-7.69399977F, -1.20000005F), new Vector2(-7.69399977F, -1.20000005F));
                    builder.AddCubicBezier(new Vector2(-7.69399977F, -1.20000005F), new Vector2(-9.46899986F, 4.24900007F), new Vector2(-9.46899986F, 4.24900007F));
                    builder.AddCubicBezier(new Vector2(-9.46899986F, 4.24900007F), new Vector2(-6.07299995F, -0.578000009F), new Vector2(-6.07299995F, -0.578000009F));
                    builder.AddCubicBezier(new Vector2(-6.07299995F, -0.578000009F), new Vector2(-5.55200005F, -7F), new Vector2(-5.55200005F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: star 2
            // - Path
            CanvasGeometry Geometry_18()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-5.55200005F, -7F));
                    builder.AddCubicBezier(new Vector2(-5.55200005F, -7F), new Vector2(-24F, -7F), new Vector2(-24F, -7F));
                    builder.AddCubicBezier(new Vector2(-24F, -7F), new Vector2(-9.46899986F, 4.24900007F), new Vector2(-9.46899986F, 4.24900007F));
                    builder.AddCubicBezier(new Vector2(-9.46899986F, 4.24900007F), new Vector2(-6.78200006F, -0.869000018F), new Vector2(-6.78200006F, -0.869000018F));
                    builder.AddCubicBezier(new Vector2(-6.78200006F, -0.869000018F), new Vector2(-5.55200005F, -7F), new Vector2(-5.55200005F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_19()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(7.7249999F, -1.29999995F));
                    builder.AddCubicBezier(new Vector2(7.7249999F, -1.29999995F), new Vector2(5.55200005F, -7F), new Vector2(5.55200005F, -7F));
                    builder.AddCubicBezier(new Vector2(5.55200005F, -7F), new Vector2(6.37799978F, -0.782000005F), new Vector2(6.37799978F, -0.782000005F));
                    builder.AddCubicBezier(new Vector2(6.37799978F, -0.782000005F), new Vector2(9.45899963F, 4.24900007F), new Vector2(9.45899963F, 4.24900007F));
                    builder.AddCubicBezier(new Vector2(9.45899963F, 4.24900007F), new Vector2(7.7249999F, -1.29999995F), new Vector2(7.7249999F, -1.29999995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: star 2
            // - Path
            CanvasGeometry Geometry_20()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(24F, -7F));
                    builder.AddCubicBezier(new Vector2(24F, -7F), new Vector2(5.55200005F, -7F), new Vector2(5.55200005F, -7F));
                    builder.AddCubicBezier(new Vector2(5.55200005F, -7F), new Vector2(6.11399984F, -0.871999979F), new Vector2(6.11399984F, -0.871999979F));
                    builder.AddCubicBezier(new Vector2(6.11399984F, -0.871999979F), new Vector2(9.45899963F, 4.24900007F), new Vector2(9.45899963F, 4.24900007F));
                    builder.AddCubicBezier(new Vector2(9.45899963F, 4.24900007F), new Vector2(24F, -7F), new Vector2(24F, -7F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: star 2
            CanvasGeometry Geometry_21()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-9.46899986F, 4.24900007F));
                    builder.AddLine(new Vector2(0F, 11.5860004F));
                    builder.AddLine(new Vector2(9.45899963F, 4.24900007F));
                    builder.AddLine(new Vector2(5.55200005F, -7F));
                    builder.AddLine(new Vector2(-5.55200005F, -7F));
                    builder.AddLine(new Vector2(-9.46899986F, 4.24900007F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostDarkOrange_FFEB7900()
            {
                return (_colorBrush_AlmostDarkOrange_FFEB7900 == null)
                    ? _colorBrush_AlmostDarkOrange_FFEB7900 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0x79, 0x00))
                    : _colorBrush_AlmostDarkOrange_FFEB7900;
            }

            CompositionColorBrush ColorBrush_AlmostGold_FFFADB00()
            {
                return (_colorBrush_AlmostGold_FFFADB00 == null)
                    ? _colorBrush_AlmostGold_FFFADB00 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFA, 0xDB, 0x00))
                    : _colorBrush_AlmostGold_FFFADB00;
            }

            CompositionColorBrush ColorBrush_AlmostOrange_FFF5BC00()
            {
                return (_colorBrush_AlmostOrange_FFF5BC00 == null)
                    ? _colorBrush_AlmostOrange_FFF5BC00 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF5, 0xBC, 0x00))
                    : _colorBrush_AlmostOrange_FFF5BC00;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape()
            {
                if (_containerShape != null) { return _containerShape; }
                var result = _containerShape = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 1.44299996F);
                result.Offset = new Vector2(24F, 24F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 6
                shapes.Add(SpriteShape_00());
                // ShapeGroup: Group 6
                shapes.Add(SpriteShape_01());
                // ShapeGroup: Group 6
                shapes.Add(SpriteShape_02());
                // ShapeGroup: Group 6
                shapes.Add(SpriteShape_03());
                // ShapeGroup: Group 6
                shapes.Add(SpriteShape_04());
                // ShapeGroup: Group 6
                shapes.Add(SpriteShape_05());
                // Transforms: star 2
                shapes.Add(SpriteShape_06());
                // Transforms: star 2
                shapes.Add(SpriteShape_07());
                // Transforms: star 2
                shapes.Add(SpriteShape_08());
                // Transforms: star 2
                shapes.Add(SpriteShape_09());
                // Transforms: star 2
                shapes.Add(SpriteShape_10());
                // Transforms: star 2
                shapes.Add(SpriteShape_11());
                return result;
            }

            CompositionPath Path_0()
            {
                if (_path_0 != null) { return _path_0; }
                var result = _path_0 = new CompositionPath(Geometry_00());
                return result;
            }

            CompositionPath Path_1()
            {
                if (_path_1 != null) { return _path_1; }
                var result = _path_1 = new CompositionPath(Geometry_02());
                return result;
            }

            CompositionPath Path_2()
            {
                if (_path_2 != null) { return _path_2; }
                var result = _path_2 = new CompositionPath(Geometry_04());
                return result;
            }

            CompositionPath Path_3()
            {
                if (_path_3 != null) { return _path_3; }
                var result = _path_3 = new CompositionPath(Geometry_06());
                return result;
            }

            CompositionPath Path_4()
            {
                if (_path_4 != null) { return _path_4; }
                var result = _path_4 = new CompositionPath(Geometry_08());
                return result;
            }

            CompositionPath Path_5()
            {
                if (_path_5 != null) { return _path_5; }
                var result = _path_5 = new CompositionPath(Geometry_11());
                return result;
            }

            CompositionPath Path_6()
            {
                if (_path_6 != null) { return _path_6; }
                var result = _path_6 = new CompositionPath(Geometry_13());
                return result;
            }

            CompositionPath Path_7()
            {
                if (_path_7 != null) { return _path_7; }
                var result = _path_7 = new CompositionPath(Geometry_15());
                return result;
            }

            CompositionPath Path_8()
            {
                if (_path_8 != null) { return _path_8; }
                var result = _path_8 = new CompositionPath(Geometry_17());
                return result;
            }

            CompositionPath Path_9()
            {
                if (_path_9 != null) { return _path_9; }
                var result = _path_9 = new CompositionPath(Geometry_19());
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 6
            CompositionPathGeometry PathGeometry_00()
            {
                if (_pathGeometry_00 != null) { return _pathGeometry_00; }
                var result = _pathGeometry_00 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 6
            CompositionPathGeometry PathGeometry_01()
            {
                if (_pathGeometry_01 != null) { return _pathGeometry_01; }
                var result = _pathGeometry_01 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 6
            CompositionPathGeometry PathGeometry_02()
            {
                if (_pathGeometry_02 != null) { return _pathGeometry_02; }
                var result = _pathGeometry_02 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 6
            CompositionPathGeometry PathGeometry_03()
            {
                if (_pathGeometry_03 != null) { return _pathGeometry_03; }
                var result = _pathGeometry_03 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 6
            CompositionPathGeometry PathGeometry_04()
            {
                if (_pathGeometry_04 != null) { return _pathGeometry_04; }
                var result = _pathGeometry_04 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 6
            CompositionPathGeometry PathGeometry_05()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_10()));
            }

            // - - Layer aggregator
            // Transforms: star 2
            CompositionPathGeometry PathGeometry_06()
            {
                if (_pathGeometry_06 != null) { return _pathGeometry_06; }
                var result = _pathGeometry_06 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // Transforms: star 2
            CompositionPathGeometry PathGeometry_07()
            {
                if (_pathGeometry_07 != null) { return _pathGeometry_07; }
                var result = _pathGeometry_07 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // Transforms: star 2
            CompositionPathGeometry PathGeometry_08()
            {
                if (_pathGeometry_08 != null) { return _pathGeometry_08; }
                var result = _pathGeometry_08 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // Transforms: star 2
            CompositionPathGeometry PathGeometry_09()
            {
                if (_pathGeometry_09 != null) { return _pathGeometry_09; }
                var result = _pathGeometry_09 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // Transforms: star 2
            CompositionPathGeometry PathGeometry_10()
            {
                if (_pathGeometry_10 != null) { return _pathGeometry_10; }
                var result = _pathGeometry_10 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // Transforms: star 2
            CompositionPathGeometry PathGeometry_11()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_21()));
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                var result = _c.CreateSpriteShape(PathGeometry_00());
                result.FillBrush = ColorBrush_AlmostGold_FFFADB00();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                var result = _c.CreateSpriteShape(PathGeometry_01());
                result.FillBrush = ColorBrush_AlmostGold_FFFADB00();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                var result = _c.CreateSpriteShape(PathGeometry_02());
                result.FillBrush = ColorBrush_AlmostGold_FFFADB00();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                var result = _c.CreateSpriteShape(PathGeometry_03());
                result.FillBrush = ColorBrush_AlmostOrange_FFF5BC00();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                var result = _c.CreateSpriteShape(PathGeometry_04());
                result.FillBrush = ColorBrush_AlmostOrange_FFF5BC00();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                var result = _c.CreateSpriteShape(PathGeometry_05());
                result.FillBrush = ColorBrush_AlmostDarkOrange_FFEB7900();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_06()
            {
                var result = _c.CreateSpriteShape(PathGeometry_06());
                result.FillBrush = ColorBrush_AlmostDarkOrange_FFEB7900();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                var result = _c.CreateSpriteShape(PathGeometry_07());
                result.FillBrush = ColorBrush_AlmostDarkOrange_FFEB7900();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                var result = _c.CreateSpriteShape(PathGeometry_08());
                result.FillBrush = ColorBrush_AlmostDarkOrange_FFEB7900();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                var result = _c.CreateSpriteShape(PathGeometry_09());
                result.FillBrush = ColorBrush_AlmostDarkOrange_FFEB7900();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_10()
            {
                var result = _c.CreateSpriteShape(PathGeometry_10());
                result.FillBrush = ColorBrush_AlmostDarkOrange_FFEB7900();
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_11()
            {
                if (_spriteShape_11 != null) { return _spriteShape_11; }
                var result = _spriteShape_11 = _c.CreateSpriteShape(PathGeometry_11());
                result.FillBrush = ColorBrush_AlmostOrange_FFF5BC00();
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Group 6
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_0(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_0(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_01()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_0(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Group 6
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_1()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_1(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_1(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_03()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_1(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Group 6
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_2()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_2(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_2(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_05()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_2(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Group 6
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_3()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_3(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_3(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_07()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_3(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Group 6
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_4()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_4(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_4(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_09()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_4(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: star 2
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_5()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_5(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_5(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_12()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_5(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: star 2
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_6()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_6(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_6(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_14()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_6(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: star 2
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_7()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_7(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_7(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_16()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_7(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: star 2
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_8()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_8(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_8(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_18()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_8(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: star 2
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_9()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_9(), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, Path_9(), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_20()), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, Path_9(), CubicBezierEasingFunction_0());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(48F, 48F);
                result.Shapes.Add(ContainerShape());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Layer aggregator
            // Transforms: star 2
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, new Vector2(0F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.107142858F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 8.
                result.InsertKeyFrame(0.285714298F, new Vector2(0.795000017F, 0.795000017F), CubicBezierEasingFunction_0());
                // Frame 14.
                result.InsertKeyFrame(0.5F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(0.714285731F, new Vector2(0.795000017F, 0.795000017F), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.892857134F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                return result;
            }

            internal StarYellow_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(48F, 48F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape.StartAnimation("Scale", ScaleVector2Animation_1(), AnimationController_0());
                _pathGeometry_00.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
                _pathGeometry_01.StartAnimation("Path", PathKeyFrameAnimation_1(), AnimationController_0());
                _pathGeometry_02.StartAnimation("Path", PathKeyFrameAnimation_2(), AnimationController_0());
                _pathGeometry_03.StartAnimation("Path", PathKeyFrameAnimation_3(), AnimationController_0());
                _pathGeometry_04.StartAnimation("Path", PathKeyFrameAnimation_4(), AnimationController_0());
                _pathGeometry_06.StartAnimation("Path", PathKeyFrameAnimation_5(), AnimationController_0());
                _pathGeometry_07.StartAnimation("Path", PathKeyFrameAnimation_6(), AnimationController_0());
                _pathGeometry_08.StartAnimation("Path", PathKeyFrameAnimation_7(), AnimationController_0());
                _pathGeometry_09.StartAnimation("Path", PathKeyFrameAnimation_8(), AnimationController_0());
                _pathGeometry_10.StartAnimation("Path", PathKeyFrameAnimation_9(), AnimationController_0());
                _spriteShape_11.StartAnimation("Scale", ScaleVector2Animation_0(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape.StopAnimation("Scale");
                _pathGeometry_00.StopAnimation("Path");
                _pathGeometry_01.StopAnimation("Path");
                _pathGeometry_02.StopAnimation("Path");
                _pathGeometry_03.StopAnimation("Path");
                _pathGeometry_04.StopAnimation("Path");
                _pathGeometry_06.StopAnimation("Path");
                _pathGeometry_07.StopAnimation("Path");
                _pathGeometry_08.StopAnimation("Path");
                _pathGeometry_09.StopAnimation("Path");
                _pathGeometry_10.StopAnimation("Path");
                _spriteShape_11.StopAnimation("Scale");
            }

        }
    }
}
