[build]
target-dir = "target"

[toolchain]
channel = "nightly"

[target.x86_64-pc-windows-msvc]
rustflags = [
  "-Z", "ehcont-guard=true",
  "-C", "control-flow-guard=true",
  "-Z", "cf-protection=full",
  "-C", "target-cpu=x86-64-v2",
  "-C", "target-feature=+crt-static",
]

[target.aarch64-pc-windows-msvc]
rustflags = [
  "-Z", "ehcont-guard=true",
  "-C", "control-flow-guard=true",
  "-C", "target-feature=+crt-static",
]

[alias]
build_x64 = "-Z build-std build --target x86_64-pc-windows-msvc --verbose --release "
build_arm64 = "-Z build-std build --target aarch64-pc-windows-msvc --verbose --release"
