//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// . xsd.exe "C:\Windows\schemas\CodeIntegrity\cipolicy.xsd" /classes /namespace:AppControlManager.SiPolicy /language:CS
//

// MIT License
//
// Copyright (c) 2023-Present - Violet Hansen - (aka HotCakeX on GitHub) - Email Address: spynetgirl@outlook.com
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// See here for more information: https://github.com/HotCakeX/Harden-Windows-Security/blob/main/LICENSE
//

namespace AppControlManager.SiPolicy
{
	public sealed class Macros
	{

		private MacrosMacro[] macroField;

		public MacrosMacro[] Macro
		{
			get
			{
				return this.macroField;
			}
			set
			{
				this.macroField = value;
			}
		}
	}

	public sealed class MacrosMacro
	{

		private string idField;

		private string valueField;

		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	public sealed class AppSetting
	{

		private string[] valueField;

		private string nameField;

		public string[] Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}
	}

	public sealed class AppRoot
	{

		private AppSetting[] settingField;

		private string manifestField;

		public AppSetting[] Setting
		{
			get
			{
				return this.settingField;
			}
			set
			{
				this.settingField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
		public string Manifest
		{
			get
			{
				return this.manifestField;
			}
			set
			{
				this.manifestField = value;
			}
		}
	}

	public sealed class AppSettingRegion
	{

		private AppRoot[] appField;

		public AppRoot[] App
		{
			get
			{
				return this.appField;
			}
			set
			{
				this.appField = value;
			}
		}
	}

	public sealed class RuleType
	{

		private OptionType itemField;

		public OptionType Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}
	}

	public enum OptionType
	{
		EnabledUMCI,
		EnabledBootMenuProtection,
		EnabledIntelligentSecurityGraphAuthorization,
		EnabledInvalidateEAsonReboot,
		RequiredWHQL,
		EnabledDeveloperModeDynamicCodeTrust,
		EnabledAllowSupplementalPolicies,
		DisabledRuntimeFilePathRuleProtection,
		EnabledRevokedExpiredAsUnsigned,
		EnabledAuditMode,
		DisabledFlightSigning,
		EnabledInheritDefaultPolicy,
		EnabledUnsignedSystemIntegrityPolicy,
		EnabledDynamicCodeSecurity,
		RequiredEVSigners,
		EnabledBootAuditOnFailure,
		EnabledAdvancedBootOptionsMenu,
		DisabledScriptEnforcement,
		RequiredEnforceStoreApplications,
		EnabledSecureSettingPolicy,
		EnabledManagedInstaller,
		EnabledUpdatePolicyNoReboot,
		EnabledConditionalWindowsLockdownPolicy,
		DisabledDefaultWindowsCertificateRemapping
	}

	public sealed class SettingValueType
	{

		private object itemField;

		[System.Xml.Serialization.XmlElementAttribute("Binary", typeof(byte[]), DataType = "hexBinary")]
		[System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(bool))]
		[System.Xml.Serialization.XmlElementAttribute("DWord", typeof(uint))]
		[System.Xml.Serialization.XmlElementAttribute("String", typeof(string))]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}
	}

	public sealed class Setting
	{

		private SettingValueType valueField;

		private string providerField;

		private string keyField;

		private string valueNameField;

		public SettingValueType Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		public string Provider
		{
			get
			{
				return this.providerField;
			}
			set
			{
				this.providerField = value;
			}
		}

		public string Key
		{
			get
			{
				return this.keyField;
			}
			set
			{
				this.keyField = value;
			}
		}

		public string ValueName
		{
			get
			{
				return this.valueNameField;
			}
			set
			{
				this.valueNameField = value;
			}
		}
	}

	public sealed class Settings
	{

		private Setting[] itemsField;

		public Setting[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	public sealed class CertEKU
	{

		private string idField;

		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	public sealed class CertOemID
	{

		private string valueField;

		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	public sealed class CertPublisher
	{

		private string valueField;

		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	public sealed class CertIssuer
	{

		private string valueField;

		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	public sealed class CertRoot
	{

		private CertEnumType typeField;

		private byte[] valueField;

		public CertEnumType Type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
		public byte[] Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	public enum CertEnumType
	{

		TBS,

		Wellknown,
	}

	public sealed class ProductSigners
	{

		private AllowedSigners allowedSignersField;

		private DeniedSigners deniedSignersField;

		private FileRulesRef fileRulesRefField;

		public AllowedSigners AllowedSigners
		{
			get
			{
				return this.allowedSignersField;
			}
			set
			{
				this.allowedSignersField = value;
			}
		}

		public DeniedSigners DeniedSigners
		{
			get
			{
				return this.deniedSignersField;
			}
			set
			{
				this.deniedSignersField = value;
			}
		}

		public FileRulesRef FileRulesRef
		{
			get
			{
				return this.fileRulesRefField;
			}
			set
			{
				this.fileRulesRefField = value;
			}
		}
	}

	public sealed class AllowedSigners
	{

		private AllowedSigner[] allowedSignerField;

		private string workaroundField;

		public AllowedSigner[] AllowedSigner
		{
			get
			{
				return this.allowedSignerField;
			}
			set
			{
				this.allowedSignerField = value;
			}
		}

		public string Workaround
		{
			get
			{
				return this.workaroundField;
			}
			set
			{
				this.workaroundField = value;
			}
		}
	}

	public sealed class AllowedSigner
	{

		private ExceptDenyRule[] exceptDenyRuleField;

		private string signerIdField;

		public ExceptDenyRule[] ExceptDenyRule
		{
			get
			{
				return this.exceptDenyRuleField;
			}
			set
			{
				this.exceptDenyRuleField = value;
			}
		}

		public string SignerId
		{
			get
			{
				return this.signerIdField;
			}
			set
			{
				this.signerIdField = value;
			}
		}
	}

	public sealed class ExceptDenyRule
	{

		private string denyRuleIDField;

		public string DenyRuleID
		{
			get
			{
				return this.denyRuleIDField;
			}
			set
			{
				this.denyRuleIDField = value;
			}
		}
	}

	public sealed class DeniedSigners
	{

		private DeniedSigner[] deniedSignerField;

		private string workaroundField;

		public DeniedSigner[] DeniedSigner
		{
			get
			{
				return this.deniedSignerField;
			}
			set
			{
				this.deniedSignerField = value;
			}
		}

		public string Workaround
		{
			get
			{
				return this.workaroundField;
			}
			set
			{
				this.workaroundField = value;
			}
		}
	}

	public sealed class DeniedSigner
	{

		private ExceptAllowRule[] exceptAllowRuleField;

		private string signerIdField;

		public ExceptAllowRule[] ExceptAllowRule
		{
			get
			{
				return this.exceptAllowRuleField;
			}
			set
			{
				this.exceptAllowRuleField = value;
			}
		}

		public string SignerId
		{
			get
			{
				return this.signerIdField;
			}
			set
			{
				this.signerIdField = value;
			}
		}
	}

	public sealed class ExceptAllowRule
	{

		private string allowRuleIDField;

		public string AllowRuleID
		{
			get
			{
				return this.allowRuleIDField;
			}
			set
			{
				this.allowRuleIDField = value;
			}
		}
	}

	public sealed class FileRulesRef
	{

		private FileRuleRef[] fileRuleRefField;

		private string workaroundField;

		public FileRuleRef[] FileRuleRef
		{
			get
			{
				return this.fileRuleRefField;
			}
			set
			{
				this.fileRuleRefField = value;
			}
		}

		public string Workaround
		{
			get
			{
				return this.workaroundField;
			}
			set
			{
				this.workaroundField = value;
			}
		}
	}

	public sealed class FileRuleRef
	{

		private string ruleIDField;

		public string RuleID
		{
			get
			{
				return this.ruleIDField;
			}
			set
			{
				this.ruleIDField = value;
			}
		}
	}

	public sealed class TestSigners
	{

		private AllowedSigners allowedSignersField;

		private DeniedSigners deniedSignersField;

		private FileRulesRef fileRulesRefField;

		public AllowedSigners AllowedSigners
		{
			get
			{
				return this.allowedSignersField;
			}
			set
			{
				this.allowedSignersField = value;
			}
		}

		public DeniedSigners DeniedSigners
		{
			get
			{
				return this.deniedSignersField;
			}
			set
			{
				this.deniedSignersField = value;
			}
		}

		public FileRulesRef FileRulesRef
		{
			get
			{
				return this.fileRulesRefField;
			}
			set
			{
				this.fileRulesRefField = value;
			}
		}
	}

	public sealed class TestSigningSigners
	{

		private AllowedSigners allowedSignersField;

		private DeniedSigners deniedSignersField;

		private FileRulesRef fileRulesRefField;

		public AllowedSigners AllowedSigners
		{
			get
			{
				return this.allowedSignersField;
			}
			set
			{
				this.allowedSignersField = value;
			}
		}

		public DeniedSigners DeniedSigners
		{
			get
			{
				return this.deniedSignersField;
			}
			set
			{
				this.deniedSignersField = value;
			}
		}

		public FileRulesRef FileRulesRef
		{
			get
			{
				return this.fileRulesRefField;
			}
			set
			{
				this.fileRulesRefField = value;
			}
		}
	}

	public sealed class AppIDTag
	{

		private string keyField;

		private string valueField;

		public string Key
		{
			get
			{
				return this.keyField;
			}
			set
			{
				this.keyField = value;
			}
		}

		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	public sealed class AppIDTags
	{

		private AppIDTag[] appIDTagField;

		private bool enforceDLLField;

		private bool enforceDLLFieldSpecified;

		public AppIDTag[] AppIDTag
		{
			get
			{
				return this.appIDTagField;
			}
			set
			{
				this.appIDTagField = value;
			}
		}

		public bool EnforceDLL
		{
			get
			{
				return this.enforceDLLField;
			}
			set
			{
				this.enforceDLLField = value;
			}
		}

		public bool EnforceDLLSpecified
		{
			get
			{
				return this.enforceDLLFieldSpecified;
			}
			set
			{
				this.enforceDLLFieldSpecified = value;
			}
		}
	}

	public sealed class FileAttribRef
	{

		private string ruleIDField;

		public string RuleID
		{
			get
			{
				return this.ruleIDField;
			}
			set
			{
				this.ruleIDField = value;
			}
		}
	}

	public sealed class EKUs
	{

		private EKU[] itemsField;

		public EKU[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	public sealed class EKU
	{

		private string idField;

		private byte[] valueField;

		private string friendlyNameField;

		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
		public byte[] Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		public string FriendlyName
		{
			get
			{
				return this.friendlyNameField;
			}
			set
			{
				this.friendlyNameField = value;
			}
		}
	}

	public sealed class FileRules
	{

		private object[] itemsField;

		[System.Xml.Serialization.XmlElementAttribute("Allow", typeof(Allow))]
		[System.Xml.Serialization.XmlElementAttribute("Deny", typeof(Deny))]
		[System.Xml.Serialization.XmlElementAttribute("FileAttrib", typeof(FileAttrib))]
		[System.Xml.Serialization.XmlElementAttribute("FileRule", typeof(FileRule))]
		public object[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	public sealed class Allow
	{

		private string idField;

		private string friendlyNameField;

		private string fileNameField;

		private string internalNameField;

		private string fileDescriptionField;

		private string productNameField;

		private string packageFamilyNameField;

		private string packageVersionField;

		private string minimumFileVersionField;

		private string maximumFileVersionField;

		private byte[] hashField;

		private string appIDsField;

		private string filePathField;

		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		public string FriendlyName
		{
			get
			{
				return this.friendlyNameField;
			}
			set
			{
				this.friendlyNameField = value;
			}
		}

		public string FileName
		{
			get
			{
				return this.fileNameField;
			}
			set
			{
				this.fileNameField = value;
			}
		}

		public string InternalName
		{
			get
			{
				return this.internalNameField;
			}
			set
			{
				this.internalNameField = value;
			}
		}

		public string FileDescription
		{
			get
			{
				return this.fileDescriptionField;
			}
			set
			{
				this.fileDescriptionField = value;
			}
		}

		public string ProductName
		{
			get
			{
				return this.productNameField;
			}
			set
			{
				this.productNameField = value;
			}
		}

		public string PackageFamilyName
		{
			get
			{
				return this.packageFamilyNameField;
			}
			set
			{
				this.packageFamilyNameField = value;
			}
		}

		public string PackageVersion
		{
			get
			{
				return this.packageVersionField;
			}
			set
			{
				this.packageVersionField = value;
			}
		}

		public string MinimumFileVersion
		{
			get
			{
				return this.minimumFileVersionField;
			}
			set
			{
				this.minimumFileVersionField = value;
			}
		}

		public string MaximumFileVersion
		{
			get
			{
				return this.maximumFileVersionField;
			}
			set
			{
				this.maximumFileVersionField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
		public byte[] Hash
		{
			get
			{
				return this.hashField;
			}
			set
			{
				this.hashField = value;
			}
		}

		public string AppIDs
		{
			get
			{
				return this.appIDsField;
			}
			set
			{
				this.appIDsField = value;
			}
		}

		public string FilePath
		{
			get
			{
				return this.filePathField;
			}
			set
			{
				this.filePathField = value;
			}
		}
	}

	public sealed class Deny
	{

		private string idField;

		private string friendlyNameField;

		private string fileNameField;

		private string internalNameField;

		private string fileDescriptionField;

		private string productNameField;

		private string packageFamilyNameField;

		private string packageVersionField;

		private string minimumFileVersionField;

		private string maximumFileVersionField;

		private byte[] hashField;

		private string appIDsField;

		private string filePathField;

		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		public string FriendlyName
		{
			get
			{
				return this.friendlyNameField;
			}
			set
			{
				this.friendlyNameField = value;
			}
		}

		public string FileName
		{
			get
			{
				return this.fileNameField;
			}
			set
			{
				this.fileNameField = value;
			}
		}

		public string InternalName
		{
			get
			{
				return this.internalNameField;
			}
			set
			{
				this.internalNameField = value;
			}
		}

		public string FileDescription
		{
			get
			{
				return this.fileDescriptionField;
			}
			set
			{
				this.fileDescriptionField = value;
			}
		}

		public string ProductName
		{
			get
			{
				return this.productNameField;
			}
			set
			{
				this.productNameField = value;
			}
		}

		public string PackageFamilyName
		{
			get
			{
				return this.packageFamilyNameField;
			}
			set
			{
				this.packageFamilyNameField = value;
			}
		}

		public string PackageVersion
		{
			get
			{
				return this.packageVersionField;
			}
			set
			{
				this.packageVersionField = value;
			}
		}

		public string MinimumFileVersion
		{
			get
			{
				return this.minimumFileVersionField;
			}
			set
			{
				this.minimumFileVersionField = value;
			}
		}

		public string MaximumFileVersion
		{
			get
			{
				return this.maximumFileVersionField;
			}
			set
			{
				this.maximumFileVersionField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
		public byte[] Hash
		{
			get
			{
				return this.hashField;
			}
			set
			{
				this.hashField = value;
			}
		}

		public string AppIDs
		{
			get
			{
				return this.appIDsField;
			}
			set
			{
				this.appIDsField = value;
			}
		}

		public string FilePath
		{
			get
			{
				return this.filePathField;
			}
			set
			{
				this.filePathField = value;
			}
		}
	}

	public sealed class FileAttrib
	{

		private string idField;

		private string friendlyNameField;

		private string fileNameField;

		private string internalNameField;

		private string fileDescriptionField;

		private string productNameField;

		private string packageFamilyNameField;

		private string packageVersionField;

		private string minimumFileVersionField;

		private string maximumFileVersionField;

		private byte[] hashField;

		private string appIDsField;

		private string filePathField;

		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		public string FriendlyName
		{
			get
			{
				return this.friendlyNameField;
			}
			set
			{
				this.friendlyNameField = value;
			}
		}

		public string FileName
		{
			get
			{
				return this.fileNameField;
			}
			set
			{
				this.fileNameField = value;
			}
		}

		public string InternalName
		{
			get
			{
				return this.internalNameField;
			}
			set
			{
				this.internalNameField = value;
			}
		}

		public string FileDescription
		{
			get
			{
				return this.fileDescriptionField;
			}
			set
			{
				this.fileDescriptionField = value;
			}
		}

		public string ProductName
		{
			get
			{
				return this.productNameField;
			}
			set
			{
				this.productNameField = value;
			}
		}

		public string PackageFamilyName
		{
			get
			{
				return this.packageFamilyNameField;
			}
			set
			{
				this.packageFamilyNameField = value;
			}
		}

		public string PackageVersion
		{
			get
			{
				return this.packageVersionField;
			}
			set
			{
				this.packageVersionField = value;
			}
		}

		public string MinimumFileVersion
		{
			get
			{
				return this.minimumFileVersionField;
			}
			set
			{
				this.minimumFileVersionField = value;
			}
		}

		public string MaximumFileVersion
		{
			get
			{
				return this.maximumFileVersionField;
			}
			set
			{
				this.maximumFileVersionField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
		public byte[] Hash
		{
			get
			{
				return this.hashField;
			}
			set
			{
				this.hashField = value;
			}
		}

		public string AppIDs
		{
			get
			{
				return this.appIDsField;
			}
			set
			{
				this.appIDsField = value;
			}
		}

		public string FilePath
		{
			get
			{
				return this.filePathField;
			}
			set
			{
				this.filePathField = value;
			}
		}
	}

	public sealed class FileRule
	{

		private string idField;

		private string friendlyNameField;

		private string fileNameField;

		private string internalNameField;

		private string fileDescriptionField;

		private string productNameField;

		private string packageFamilyNameField;

		private string packageVersionField;

		private string minimumFileVersionField;

		private string maximumFileVersionField;

		private byte[] hashField;

		private string appIDsField;

		private string filePathField;

		private RuleTypeType typeField;

		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		public string FriendlyName
		{
			get
			{
				return this.friendlyNameField;
			}
			set
			{
				this.friendlyNameField = value;
			}
		}

		public string FileName
		{
			get
			{
				return this.fileNameField;
			}
			set
			{
				this.fileNameField = value;
			}
		}

		public string InternalName
		{
			get
			{
				return this.internalNameField;
			}
			set
			{
				this.internalNameField = value;
			}
		}

		public string FileDescription
		{
			get
			{
				return this.fileDescriptionField;
			}
			set
			{
				this.fileDescriptionField = value;
			}
		}

		public string ProductName
		{
			get
			{
				return this.productNameField;
			}
			set
			{
				this.productNameField = value;
			}
		}

		public string PackageFamilyName
		{
			get
			{
				return this.packageFamilyNameField;
			}
			set
			{
				this.packageFamilyNameField = value;
			}
		}

		public string PackageVersion
		{
			get
			{
				return this.packageVersionField;
			}
			set
			{
				this.packageVersionField = value;
			}
		}

		public string MinimumFileVersion
		{
			get
			{
				return this.minimumFileVersionField;
			}
			set
			{
				this.minimumFileVersionField = value;
			}
		}

		public string MaximumFileVersion
		{
			get
			{
				return this.maximumFileVersionField;
			}
			set
			{
				this.maximumFileVersionField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
		public byte[] Hash
		{
			get
			{
				return this.hashField;
			}
			set
			{
				this.hashField = value;
			}
		}

		public string AppIDs
		{
			get
			{
				return this.appIDsField;
			}
			set
			{
				this.appIDsField = value;
			}
		}

		public string FilePath
		{
			get
			{
				return this.filePathField;
			}
			set
			{
				this.filePathField = value;
			}
		}

		public RuleTypeType Type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
	}

	public enum RuleTypeType
	{

		Match,

		Exclude,

		Attribute,
	}

	public sealed class UpdatePolicySigner
	{

		private string signerIdField;

		public string SignerId
		{
			get
			{
				return this.signerIdField;
			}
			set
			{
				this.signerIdField = value;
			}
		}
	}

	public sealed class UpdatePolicySigners
	{

		private UpdatePolicySigner[] itemsField;

		public UpdatePolicySigner[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	public sealed class SupplementalPolicySigner
	{

		private string signerIdField;

		public string SignerId
		{
			get
			{
				return this.signerIdField;
			}
			set
			{
				this.signerIdField = value;
			}
		}
	}

	public sealed class SupplementalPolicySigners
	{

		private SupplementalPolicySigner[] itemsField;

		public SupplementalPolicySigner[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	public sealed class CiSigner
	{

		private string signerIdField;

		public string SignerId
		{
			get
			{
				return this.signerIdField;
			}
			set
			{
				this.signerIdField = value;
			}
		}
	}

	public sealed class CiSigners
	{

		private CiSigner[] itemsField;

		public CiSigner[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	public sealed class Signers
	{

		private Signer[] itemsField;

		public Signer[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	public sealed class Signer
	{

		private CertRoot certRootField;

		private CertEKU[] certEKUField;

		private CertIssuer certIssuerField;

		private CertPublisher certPublisherField;

		private CertOemID certOemIDField;

		private FileAttribRef[] fileAttribRefField;

		private string nameField;

		private string idField;

		private System.DateTime signTimeAfterField;

		private bool signTimeAfterFieldSpecified;

		public CertRoot CertRoot
		{
			get
			{
				return this.certRootField;
			}
			set
			{
				this.certRootField = value;
			}
		}

		public CertEKU[] CertEKU
		{
			get
			{
				return this.certEKUField;
			}
			set
			{
				this.certEKUField = value;
			}
		}

		public CertIssuer CertIssuer
		{
			get
			{
				return this.certIssuerField;
			}
			set
			{
				this.certIssuerField = value;
			}
		}

		public CertPublisher CertPublisher
		{
			get
			{
				return this.certPublisherField;
			}
			set
			{
				this.certPublisherField = value;
			}
		}

		public CertOemID CertOemID
		{
			get
			{
				return this.certOemIDField;
			}
			set
			{
				this.certOemIDField = value;
			}
		}

		public FileAttribRef[] FileAttribRef
		{
			get
			{
				return this.fileAttribRefField;
			}
			set
			{
				this.fileAttribRefField = value;
			}
		}

		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		public System.DateTime SignTimeAfter
		{
			get
			{
				return this.signTimeAfterField;
			}
			set
			{
				this.signTimeAfterField = value;
			}
		}

		public bool SignTimeAfterSpecified
		{
			get
			{
				return this.signTimeAfterFieldSpecified;
			}
			set
			{
				this.signTimeAfterFieldSpecified = value;
			}
		}
	}

	public sealed class SigningScenarios
	{

		private SigningScenario[] itemsField;

		public SigningScenario[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	public sealed class SigningScenario
	{

		private ProductSigners productSignersField;

		private TestSigners testSignersField;

		private TestSigningSigners testSigningSignersField;

		private AppIDTags appIDTagsField;

		private string idField;

		private string friendlyNameField;

		private byte valueField;

		private string inheritedScenariosField;

		private ushort minimumHashAlgorithmField;

		private bool minimumHashAlgorithmFieldSpecified;

		public ProductSigners ProductSigners
		{
			get
			{
				return this.productSignersField;
			}
			set
			{
				this.productSignersField = value;
			}
		}

		public TestSigners TestSigners
		{
			get
			{
				return this.testSignersField;
			}
			set
			{
				this.testSignersField = value;
			}
		}

		public TestSigningSigners TestSigningSigners
		{
			get
			{
				return this.testSigningSignersField;
			}
			set
			{
				this.testSigningSignersField = value;
			}
		}

		public AppIDTags AppIDTags
		{
			get
			{
				return this.appIDTagsField;
			}
			set
			{
				this.appIDTagsField = value;
			}
		}

		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		public string FriendlyName
		{
			get
			{
				return this.friendlyNameField;
			}
			set
			{
				this.friendlyNameField = value;
			}
		}

		public byte Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		public string InheritedScenarios
		{
			get
			{
				return this.inheritedScenariosField;
			}
			set
			{
				this.inheritedScenariosField = value;
			}
		}

		public ushort MinimumHashAlgorithm
		{
			get
			{
				return this.minimumHashAlgorithmField;
			}
			set
			{
				this.minimumHashAlgorithmField = value;
			}
		}

		public bool MinimumHashAlgorithmSpecified
		{
			get
			{
				return this.minimumHashAlgorithmFieldSpecified;
			}
			set
			{
				this.minimumHashAlgorithmFieldSpecified = value;
			}
		}
	}

	public sealed class SiPolicy
	{

		private string versionExField;

		private string policyTypeIDField;

		private string platformIDField;

		private string policyIDField;

		private string basePolicyIDField;

		private RuleType[] rulesField;

		private EKU[] eKUsField;

		private object[] fileRulesField;

		private Signer[] signersField;

		private SigningScenario[] signingScenariosField;

		private UpdatePolicySigner[] updatePolicySignersField;

		private CiSigner[] ciSignersField;

		private uint hvciOptionsField;

		private bool hvciOptionsFieldSpecified;

		private Setting[] settingsField;

		private MacrosMacro[] macrosField;

		private SupplementalPolicySigner[] supplementalPolicySignersField;

		private AppSettingRegion appSettingsField;

		private string friendlyNameField;

		private PolicyType policyTypeField;

		private bool policyTypeFieldSpecified;

		public string VersionEx
		{
			get
			{
				return this.versionExField;
			}
			set
			{
				this.versionExField = value;
			}
		}

		public string PolicyTypeID
		{
			get
			{
				return this.policyTypeIDField;
			}
			set
			{
				this.policyTypeIDField = value;
			}
		}

		public string PlatformID
		{
			get
			{
				return this.platformIDField;
			}
			set
			{
				this.platformIDField = value;
			}
		}

		public string PolicyID
		{
			get
			{
				return this.policyIDField;
			}
			set
			{
				this.policyIDField = value;
			}
		}

		public string BasePolicyID
		{
			get
			{
				return this.basePolicyIDField;
			}
			set
			{
				this.basePolicyIDField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("Rule", IsNullable = false)]
		public RuleType[] Rules
		{
			get
			{
				return this.rulesField;
			}
			set
			{
				this.rulesField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("EKU", IsNullable = false)]
		public EKU[] EKUs
		{
			get
			{
				return this.eKUsField;
			}
			set
			{
				this.eKUsField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("Allow", typeof(Allow), IsNullable = false)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Deny", typeof(Deny), IsNullable = false)]
		[System.Xml.Serialization.XmlArrayItemAttribute("FileAttrib", typeof(FileAttrib), IsNullable = false)]
		[System.Xml.Serialization.XmlArrayItemAttribute("FileRule", typeof(FileRule), IsNullable = false)]
		public object[] FileRules
		{
			get
			{
				return this.fileRulesField;
			}
			set
			{
				this.fileRulesField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("Signer", IsNullable = false)]
		public Signer[] Signers
		{
			get
			{
				return this.signersField;
			}
			set
			{
				this.signersField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("SigningScenario", IsNullable = false)]
		public SigningScenario[] SigningScenarios
		{
			get
			{
				return this.signingScenariosField;
			}
			set
			{
				this.signingScenariosField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("UpdatePolicySigner", IsNullable = false)]
		public UpdatePolicySigner[] UpdatePolicySigners
		{
			get
			{
				return this.updatePolicySignersField;
			}
			set
			{
				this.updatePolicySignersField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("CiSigner", IsNullable = false)]
		public CiSigner[] CiSigners
		{
			get
			{
				return this.ciSignersField;
			}
			set
			{
				this.ciSignersField = value;
			}
		}

		public uint HvciOptions
		{
			get
			{
				return this.hvciOptionsField;
			}
			set
			{
				this.hvciOptionsField = value;
			}
		}

		public bool HvciOptionsSpecified
		{
			get
			{
				return this.hvciOptionsFieldSpecified;
			}
			set
			{
				this.hvciOptionsFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable = false)]
		public Setting[] Settings
		{
			get
			{
				return this.settingsField;
			}
			set
			{
				this.settingsField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("Macro", IsNullable = false)]
		public MacrosMacro[] Macros
		{
			get
			{
				return this.macrosField;
			}
			set
			{
				this.macrosField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("SupplementalPolicySigner", IsNullable = false)]
		public SupplementalPolicySigner[] SupplementalPolicySigners
		{
			get
			{
				return this.supplementalPolicySignersField;
			}
			set
			{
				this.supplementalPolicySignersField = value;
			}
		}

		public AppSettingRegion AppSettings
		{
			get
			{
				return this.appSettingsField;
			}
			set
			{
				this.appSettingsField = value;
			}
		}

		public string FriendlyName
		{
			get
			{
				return this.friendlyNameField;
			}
			set
			{
				this.friendlyNameField = value;
			}
		}

		public PolicyType PolicyType
		{
			get
			{
				return this.policyTypeField;
			}
			set
			{
				this.policyTypeField = value;
			}
		}

		public bool PolicyTypeSpecified
		{
			get
			{
				return this.policyTypeFieldSpecified;
			}
			set
			{
				this.policyTypeFieldSpecified = value;
			}
		}
	}

	public enum PolicyType
	{
		BasePolicy,
		SupplementalPolicy,
		AppIDTaggingPolicy,
	}
}
