[package]
name = "exploit_mitigations"
version = "1.0.0"
edition = "2024"
authors = ["Violet Hansen"]
license = "MIT"
homepage = "https://github.com/HotCakeX/Harden-Windows-Security"
repository = "https://github.com/HotCakeX/Harden-Windows-Security"
publish = false
rust-version = "1.90"

[lib]
name = "exploit_mitigations_lib"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "exploit_mitigations_bin"
path = "src/main.rs"

[profile.release]
codegen-units = 1
opt-level = "s"
split-debuginfo = "packed"
strip = "symbols"
lto = "fat"
incremental = false
panic = "unwind"

[dependencies]
windows = { version = "*", features = [
    "Win32_System_Registry",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics",
    "Win32_System_SystemInformation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_Security",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common"
] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
