[package]
name = "exploit_mitigations"
version = "1.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
name = "exploit_mitigations_lib"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "exploit_mitigations_bin"
path = "src/main.rs"

[dependencies]
windows = { version = "*", features = [
    "Win32_System_Registry",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics",
    "Win32_System_SystemInformation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_Security",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common"
] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
