[build]
target-dir = "target"

[alias]
build_x64 = "-Z build-std build --target x86_64-pc-windows-msvc --verbose --release"
build_arm64 = "-Z build-std build --target aarch64-pc-windows-msvc --verbose --release"
