[package]
name = "DeviceGuardInfoRetrievalWMI"
version = "1.0.0"
edition = "2024"
description = "Library used to return serialized JSON string of the Device Guard configurations retrieved via WMI."
documentation = "https://github.com/HotCakeX/Harden-Windows-Security"
homepage = "https://github.com/HotCakeX/Harden-Windows-Security"
repository = "https://github.com/HotCakeX/Harden-Windows-Security"
license = "MIT"
keywords = ["WMI", "Windows", "Security"]
categories = ["API bindings", "Security"]
publish = false
rust-version = "1.87" # Enforces minimum required installed Rust version

[profile.release]
opt-level = 3
overflow-checks = true
lto = "fat"
incremental = true

[dependencies]
windows = { version = "0.61.*", features = [    "Win32_Security",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Ole",
    "Win32_Foundation",
    "Win32_System_Rpc",
    "Win32_System_Variant",
    "Win32_System_Wmi"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib", "rlib"]
